import assert from 'node:assert/strict';
import {mergeHistory,analyze,changeAt,validateBackup} from '../market.mjs';
const now=Date.now(),H=3600000;
const rows=Array.from({length:9},(_,i)=>({game:'fc27',platform:'pc',card_id:'1',name:'Example',market_price:4000+i*100,updated_at:new Date(now-(8-i)*H).toISOString()}));
let history=mergeHistory({},rows);assert.equal(history['1'].points.length,9);history=mergeHistory(history,rows);assert.equal(history['1'].points.length,9);
assert.equal(analyze(history['1'],[],now).direction,'Sygnał wzrostowy');
assert.equal(analyze(mergeHistory({},rows.slice(-1))['1'],[],now).direction,'Za mało danych');
assert.equal(analyze(history['1'],[],now+H).direction,'Nieaktualne ceny');
const event={id:'e',title:'SBC',type:'sbc',scope:'fodder',ids:[],start:now-H,end:now+H,created:now-H};
assert.equal(analyze(history['1'],[event],now).active,0);history['1'].category='fodder';assert.equal(analyze(history['1'],[event],now).active,1);
assert.equal(analyze(history['1'],[{...event,created:now+H}],now).active,0);
assert.equal(analyze(history['1'],[{...event,end:now}],now).active,0);
assert.equal(changeAt(history['1'].points,24),null);
assert.equal(Object.keys(mergeHistory({},[{...rows[0],market_price:0}])).length,0);
assert.equal(validateBackup({schema:1,history,events:[event]}).events.length,1);
assert.throws(()=>validateBackup({schema:1,history:{bad:{id:'bad',name:'x',category:'unknown',points:[{t:1,price:NaN}]}},events:[]}));
console.log('Market history and event signal checks passed.');

const avgCard={id:'avg',name:'Average only',category:'unknown',points:[],averages:{hourly:Array.from({length:5},(_,i)=>({t:now-(4-i)*H,price:1000+i*100})),daily:[]}};
const avgResult=analyze(avgCard,[],now);
assert.equal(avgResult.basis,'hourly');assert.equal(avgResult.analysisPoints.length,4);
assert.match(avgResult.direction,/Trend wzrostowy/);assert.equal(avgResult.last,undefined);
assert.equal(avgResult.delta6,null);assert.equal(avgResult.points.length,0);
const dailyCard={...avgCard,averages:{hourly:[],daily:Array.from({length:8},(_,i)=>({t:now-(8-i)*24*H,price:2000-i*100}))}};
assert.equal(analyze(dailyCard,[],now).basis,'daily');
assert.match(analyze(dailyCard,[],now).direction,/Trend spadkowy/);
assert.match(analyze(dailyCard,[],now+100*H).direction,/Historyczny trend/);
assert.equal(analyze({...avgCard,averages:{hourly:avgCard.averages.hourly.slice(-3),daily:[]}},[],now).basis,undefined);
assert.equal(analyze({...dailyCard,points:history['1'].points},[],now).basis,'live');
console.log('Hourly/daily fallback, completed buckets, stale history and live precedence passed.');
